mqtt:
  hostname: 127.0.0.1
  port: 1234 #defaults to 1883
  user: test
  password: test
deviceName: system_sensors_
client_id: system_sensors_
timezone: America/Los_Angeles
update_interval: 60 #Defaults to 60
# external_drives:
#   Drive1: /boot/